#!/bin/sh
#SBATCH --error=/gpfs/projects/bsc40/mschikora/scripts/perSVade/perSVade_repository/testing/cross_accuracy_calculations_realSVs_onlyHuman_trainOnSimulationsDatasets/cross_accuracy_human/cross_accuracy_files/STDfiles/getting_crossAccuracy_stderr.txt
#SBATCH --output=/gpfs/projects/bsc40/mschikora/scripts/perSVade/perSVade_repository/testing/cross_accuracy_calculations_realSVs_onlyHuman_trainOnSimulationsDatasets/cross_accuracy_human/cross_accuracy_files/STDfiles/getting_crossAccuracy_stdout.txt
#SBATCH --job-name=getting_crossAccuracy
#SBATCH --get-user-env
#SBATCH --workdir=/gpfs/projects/bsc40/mschikora/scripts/perSVade/perSVade_repository/testing/cross_accuracy_calculations_realSVs_onlyHuman_trainOnSimulationsDatasets/cross_accuracy_human/cross_accuracy_files
#SBATCH --time=02:00:00
#SBATCH --qos=debug
#SBATCH --cpus-per-task=8
#SBATCH --ntasks=48


module load greasy
export GREASY_LOGFILE=/gpfs/projects/bsc40/mschikora/scripts/perSVade/perSVade_repository/testing/cross_accuracy_calculations_realSVs_onlyHuman_trainOnSimulationsDatasets/cross_accuracy_human/cross_accuracy_files/STDfiles/getting_crossAccuracy_greasy.log;
echo 'running pipeline';
greasy /gpfs/projects/bsc40/mschikora/scripts/perSVade/perSVade_repository/testing/cross_accuracy_calculations_realSVs_onlyHuman_trainOnSimulationsDatasets/cross_accuracy_human/cross_accuracy_files/jobs.getting_crossAccuracy