name: Stale Issues and Pull Requests
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Check for stale issues and pull requests
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.SECRET_TOKEN }}
          stale-issue-message: 'This issue is marked as stale by the stale_bot.'
          stale-pr-message: 'This pull request is marked as stale by the stale_bot.'
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: stale
          stale-pr-label: stale
          close-issue-label: closed
          exempt-issue-labels: 'in-progress, bug, enhancement, pinned'
          exempt-pr-labels: 'work-in-progress, bug'
